[project]
name = "atria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "openapi-python-client>=0.25.2",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "faker>=37.4.2",
    "ipykernel>=6.29.5",
]
